#!/usr/bin/env bash
xvfbFound=false 
foundDisplay=false
i=0
x=0
typeFile=".X*-lock" #pattern to only select Xvfb tmp file
findDisplayNumber(){
for inode in $(ls $1/$typeFile)
do
	owner=$(ls -al $inode | grep -v grep |  awk '{ print $3; }')
	array[$i]=$(echo "$inode" | tr -d [:alpha:] | tr -d [:punct:]) #make a list of all the display number for, in another case find a free number
	if [ "$USER" = "$owner" ];then
		xvfbFound=true
		var=$(echo "$inode" | tr -d [:alpha:] | tr -d [:punct:]) 
		echo $var #return the availaible display for the logged user
 		break;
	fi
	let i++
done
if  [ $xvfbFound=="false" ]; then #if no display found
	var1=${#array[@]}
	for (( c=0; c<var1; c++ ))
	do
		if [ $x -ne ${array[$c]} ];then
			var=$x			
			foundDisplay=true
			echo $var #if no display is already created, this function will return a free number display
			break;
		fi
		let x++
	done
	if  [ $foundDisplay=="false" ]; then
	var=$x
	fi	
fi
}
