#!/bin/sh
Xvfb :2 &
export DISPLAY=:2
cd /scisoft/jenkins/ub1204_opid14/squish-4.2.3-java-linux64/bin/
./squishserver & >/$WORKSPACE/serverlog
sleep 1
/scisoft/jenkins/ub1204_opid14/squish-4.2.3-java-linux64/bin/squishrunner --testsuite /scisoft/jenkins/ub1204_opid14/workspace/Dawn_squish_tests_production/org.dawnsci.squishtests/$1/ --testcase $2/ --useWaitFor>>/$WORKSPACE/log/$1_squishlog 
var1=$(ps -aef |grep squishserver | grep -v grep | awk '{ print $2; }' |  head -1)
kill -9 $var1
var2=$(ps -aef |grep Xvfb | grep -v grep | awk '{ print $2; }' |  head -1)
kill -9 $var2

